name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  # Runs on push to the main branch (you can change this as needed)

jobs:
  build:
    runs-on: ubuntu-latest  # The GitHub Actions runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your code from the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx (optional but allows multi-platform builds)

    - name: Log in to Azure
      uses: azure/login@v1  # Azure login step
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure credentials stored in GitHub Secrets

    - name: Build Docker image
      run: |
        docker build -t attrition.azurecr.io/my-ml-app:v1 .  # Build the Docker image

    - name: Log in to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login attrition.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin  # Log in to Azure Container Registry (ACR)

    - name: Push Docker image to ACR
      run: |
        docker push attrition.azurecr.io/my-ml-app:v1  # Push the Docker image to ACR

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create --name attritionml \
          --resource-group Kush2 \
          --image attrition.azurecr.io/my-ml-app:v1 \
          --registry-server attrition.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --ingress external \
          --target-port 5000 \
          --environment attritionml-env  # Deploy to Azure Container Apps
